/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AmbassadorService } from "../ambassador.service";
import { AmbassadorCreateInput } from "./AmbassadorCreateInput";
import { Ambassador } from "./Ambassador";
import { AmbassadorFindManyArgs } from "./AmbassadorFindManyArgs";
import { AmbassadorWhereUniqueInput } from "./AmbassadorWhereUniqueInput";
import { AmbassadorUpdateInput } from "./AmbassadorUpdateInput";

export class AmbassadorControllerBase {
  constructor(protected readonly service: AmbassadorService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Ambassador })
  async createAmbassador(
    @common.Body() data: AmbassadorCreateInput
  ): Promise<Ambassador> {
    return await this.service.createAmbassador({
      data: data,
      select: {
        createdAt: true,
        document: true,
        email: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Ambassador] })
  @ApiNestedQuery(AmbassadorFindManyArgs)
  async ambassadors(@common.Req() request: Request): Promise<Ambassador[]> {
    const args = plainToClass(AmbassadorFindManyArgs, request.query);
    return this.service.ambassadors({
      ...args,
      select: {
        createdAt: true,
        document: true,
        email: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Ambassador })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async ambassador(
    @common.Param() params: AmbassadorWhereUniqueInput
  ): Promise<Ambassador | null> {
    const result = await this.service.ambassador({
      where: params,
      select: {
        createdAt: true,
        document: true,
        email: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Ambassador })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateAmbassador(
    @common.Param() params: AmbassadorWhereUniqueInput,
    @common.Body() data: AmbassadorUpdateInput
  ): Promise<Ambassador | null> {
    try {
      return await this.service.updateAmbassador({
        where: params,
        data: data,
        select: {
          createdAt: true,
          document: true,
          email: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Ambassador })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteAmbassador(
    @common.Param() params: AmbassadorWhereUniqueInput
  ): Promise<Ambassador | null> {
    try {
      return await this.service.deleteAmbassador({
        where: params,
        select: {
          createdAt: true,
          document: true,
          email: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
