/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Ambassador } from "./Ambassador";
import { AmbassadorCountArgs } from "./AmbassadorCountArgs";
import { AmbassadorFindManyArgs } from "./AmbassadorFindManyArgs";
import { AmbassadorFindUniqueArgs } from "./AmbassadorFindUniqueArgs";
import { CreateAmbassadorArgs } from "./CreateAmbassadorArgs";
import { UpdateAmbassadorArgs } from "./UpdateAmbassadorArgs";
import { DeleteAmbassadorArgs } from "./DeleteAmbassadorArgs";
import { AmbassadorService } from "../ambassador.service";
@graphql.Resolver(() => Ambassador)
export class AmbassadorResolverBase {
  constructor(protected readonly service: AmbassadorService) {}

  async _ambassadorsMeta(
    @graphql.Args() args: AmbassadorCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Ambassador])
  async ambassadors(
    @graphql.Args() args: AmbassadorFindManyArgs
  ): Promise<Ambassador[]> {
    return this.service.ambassadors(args);
  }

  @graphql.Query(() => Ambassador, { nullable: true })
  async ambassador(
    @graphql.Args() args: AmbassadorFindUniqueArgs
  ): Promise<Ambassador | null> {
    const result = await this.service.ambassador(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Ambassador)
  async createAmbassador(
    @graphql.Args() args: CreateAmbassadorArgs
  ): Promise<Ambassador> {
    return await this.service.createAmbassador({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Ambassador)
  async updateAmbassador(
    @graphql.Args() args: UpdateAmbassadorArgs
  ): Promise<Ambassador | null> {
    try {
      return await this.service.updateAmbassador({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Ambassador)
  async deleteAmbassador(
    @graphql.Args() args: DeleteAmbassadorArgs
  ): Promise<Ambassador | null> {
    try {
      return await this.service.deleteAmbassador(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
