/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Ambassador as PrismaAmbassador } from "@prisma/client";

export class AmbassadorServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.AmbassadorCountArgs, "select">
  ): Promise<number> {
    return this.prisma.ambassador.count(args);
  }

  async ambassadors(
    args: Prisma.AmbassadorFindManyArgs
  ): Promise<PrismaAmbassador[]> {
    return this.prisma.ambassador.findMany(args);
  }
  async ambassador(
    args: Prisma.AmbassadorFindUniqueArgs
  ): Promise<PrismaAmbassador | null> {
    return this.prisma.ambassador.findUnique(args);
  }
  async createAmbassador(
    args: Prisma.AmbassadorCreateArgs
  ): Promise<PrismaAmbassador> {
    return this.prisma.ambassador.create(args);
  }
  async updateAmbassador(
    args: Prisma.AmbassadorUpdateArgs
  ): Promise<PrismaAmbassador> {
    return this.prisma.ambassador.update(args);
  }
  async deleteAmbassador(
    args: Prisma.AmbassadorDeleteArgs
  ): Promise<PrismaAmbassador> {
    return this.prisma.ambassador.delete(args);
  }
}
